# Generated by Django 3.1.5 on 2021-01-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteInversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='id_fuente_inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimiento.fuenteinversion'),
        ),
    ]
